import type { DeviceStatus, KeymapDocument } from "../../../../shared/protocol/auto-typer-protocol";
import { currentFeiyu200Keymap } from "./keymap";

const mockMotor = (id: number) => ({
  id,
  hasVelocity: true,
  hasRealtimeAngle: false,
  hasInputPulse: true,
  hasStatus: true,
  velocityRpm: 0,
  realtimeAngleRaw65536: 0,
  inputPulseSteps: 0,
  statusFlags: 0,
  driverFault: false,
  conditionNotMet: false,
  commandMalformed: false,
  lastAckCommand: 0,
  lastConditionNotMetCommand: 0,
  lastMalformedCommand: 0,
  lastAckMs: 0,
  lastConditionNotMetMs: 0,
  lastMalformedMs: 0,
  motionReached: false,
  lastMotionReachedMs: 0,
  lastVelocityMs: 0,
  lastRealtimeAngleMs: 0,
  lastInputPulseMs: 0,
  lastStatusMs: 0,
  lastAnyFrameMs: 0,
});

export const mockStatus: DeviceStatus = {
  deviceId: "esp32-s3-auto-typer",
  firmwareVersion: "0.1.0",
  ipAddress: "192.168.4.42",
  mode: "idle",
  health: "ok",
  wifiRssi: -48,
  servoReady: true,
  motionReady: true,
  keymapVersion: 1,
  currentJob: undefined,
  canDiagnostics: {
    driverReady: true,
    motionReady: true,
    fatalFault: false,
    recoverable: true,
    lastAlerts: 0,
    txFailedCount: 0,
    txRetryCount: 0,
    busErrorCount: 0,
    rxQueueFullCount: 0,
    errPassiveCount: 0,
    busOffCount: 0,
    pendingFrameValid: false,
    lastAlertAtMs: 0,
    lastFaultAtMs: 0,
    lastTxError: "",
    lastFaultCode: "",
    lastFaultMessage: "",
  },
  motors: [
    mockMotor(1),
    mockMotor(2),
    mockMotor(3),
    mockMotor(4),
  ],
};

export const mockKeymap: KeymapDocument = currentFeiyu200Keymap();
